# Generated by Django 5.0.4 on 2024-05-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
