# Generated by Django 5.0.4 on 2024-05-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_app",
            "0004_alter_logs_options_alter_profile_options_project_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(default="", max_length=255),
        ),
    ]
