# Generated by Django 5.0.4 on 2024-05-19 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0005_project_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="project",
            name="rating",
        ),
        migrations.AlterField(
            model_name="comment",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(default="No description provided", max_length=255),
        ),
        migrations.CreateModel(
            name="CommentRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_liked", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="django_app.comment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment Rating",
                "verbose_name_plural": "Comment Ratings",
                "unique_together": {("author", "comment")},
            },
        ),
        migrations.CreateModel(
            name="ProjectRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_liked", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="django_app.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Rating",
                "verbose_name_plural": "Project Ratings",
                "unique_together": {("author", "project")},
            },
        ),
    ]
