# Generated by Django 5.0.4 on 2024-05-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0006_remove_comment_rating_remove_project_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
    ]
