# Generated by Django 5.0.4 on 2024-05-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0008_remove_profile_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
