# Generated by Django 5.0.4 on 2024-05-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0009_comment_rating_project_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="project",
            name="rating",
        ),
    ]
